package us.mn.hennepin.co.service.sils.searchservice._2_1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-31T20:55:17.782-05:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://www.co.hennepin.mn.us/service/sils/SearchService/2.1", name = "SubjectSearchPort")
@XmlSeeAlso({us.mn.hennepin.co.justice.ObjectFactory.class, gov.ojp.it.jxdm.nibrs_misc._1.ObjectFactory.class, gov.ojp.it.jxdm.usps_states._1.ObjectFactory.class, gov.ojp.it.jxdm.mn_offense._1.ObjectFactory.class, us.mn.hennepin.co.justice.silsservicemessage.ObjectFactory.class, gov.ojp.it.jxdm._3_0.ObjectFactory.class, gov.ojp.it.jxdm.ncic_2000._1_0.ObjectFactory.class, us.mn.hennepin.co.common.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SubjectSearchPort {

    /**
     * Multiple criteria search combines multiple searches by subject id, activity and name.
     */
    @WebResult(name = "ReplySearchMulti", targetNamespace = "http://www.co.hennepin.mn.us/Justice/SILSServiceMessage", partName = "result")
    @WebMethod(action = "http://www.co.hennepin.mn.us/service/sils/SubjectSearchService/2.1/searchSubjectSummaries")
    public us.mn.hennepin.co.justice.silsservicemessage.ReplySearchMulti searchSubjectSummaries(
        @WebParam(partName = "criteria", name = "RequestSearchMulti", targetNamespace = "http://www.co.hennepin.mn.us/Justice/SILSServiceMessage")
        us.mn.hennepin.co.justice.silsservicemessage.RequestSearchMulti criteria
    ) throws ReplyExceptionMessage;

    /**
     * Returns subject detail information by an activity
     */
    @WebResult(name = "ReplySearchDetail", targetNamespace = "http://www.co.hennepin.mn.us/Justice/SILSServiceMessage", partName = "result")
    @WebMethod(action = "http://www.co.hennepin.mn.us/service/sils/SubjectSearchService/2.1/searchSubjectByActivity")
    public us.mn.hennepin.co.justice.silsservicemessage.ReplySearchDetail searchSubjectByActivity(
        @WebParam(partName = "criteria", name = "RequestSearchActivityID", targetNamespace = "http://www.co.hennepin.mn.us/Justice/SILSServiceMessage")
        gov.ojp.it.jxdm._3_0.ActivityIdType criteria
    ) throws ReplyExceptionMessage;

    /**
     * Returns SILS reference tables and selected codes
     */
    @WebResult(name = "ReplyReference", targetNamespace = "http://www.co.hennepin.mn.us/Justice/SILSServiceMessage", partName = "result")
    @WebMethod(action = "http://www.co.hennepin.mn.us/service/sils/SubjectSearchService/2.0/getReferenceValues")
    public us.mn.hennepin.co.justice.silsservicemessage.ReplyReference getReferenceValues(
        @WebParam(partName = "criteria", name = "RequestReference", targetNamespace = "http://www.co.hennepin.mn.us/Justice/SILSServiceMessage")
        us.mn.hennepin.co.justice.silsservicemessage.RequestReference criteria
    ) throws ReplyExceptionMessage;

    /**
     * Returns subject detail information by a subject id
     */
    @WebResult(name = "ReplySearchDetail", targetNamespace = "http://www.co.hennepin.mn.us/Justice/SILSServiceMessage", partName = "result")
    @WebMethod(action = "http://www.co.hennepin.mn.us/service/sils/SubjectSearchService/2.1/searchSubjectByNumber")
    public us.mn.hennepin.co.justice.silsservicemessage.ReplySearchDetail searchSubjectByNumber(
        @WebParam(partName = "criteria", name = "RequestSearchPersonID", targetNamespace = "http://www.co.hennepin.mn.us/Justice/SILSServiceMessage")
        us.mn.hennepin.co.justice.silsservicemessage.RequestSearchPersonID criteria
    ) throws ReplyExceptionMessage;
}
